Add bill command
AY2223S1-CS2103T-W16-1/tp pull request #104
Opened 2022-10-16 18:04 UTC by JustinPeng13

## Added
- BillCommand class
- BillCommandParser class
- BillCommandTest class
- BillCommandParserTest class
- Bill command in user guide
- Bill prefix "b/"
- Add method for bill
## Modified
- Bill accepts negative values but not for final bill
- Test data
- Sample data
## Comments
- Bill command and bill class can accept +, -, or unsigned (taken as positive) values
- Bill is checked for negative value before being assigned to guest

Resolves #99, resolves #82, resolves #83, resolves #81

2022-10-17 12:23 UTC, jehousoh requested changes
Left some comments do let me know what you think! Good work~

2022-10-17 12:23 UTC, jehousoh commented on docs/UserGuide.md
> +Format: `bill INDEX b/BILL`
Should you add the [] on BILL to follow the style of the other commands?

2022-10-17 12:23 UTC, jehousoh commented on src/main/java/seedu/guest/model/guest/Bill.java
> +                    + "If a decimal point is used, there must be 2 digits after it (e.g., 9.99).\n"
Should we allow 0 or 1 digit to be more flexible?

2022-10-17 12:23 UTC, jehousoh commented on src/test/java/seedu/guest/logic/commands/BillCommandTest.java
> +    public void execute_invalidGuestIndexFilteredList_failure() {
Should we add a test for negativeBill as well?

2022-10-18 06:35 UTC, JustinPeng13 commented on docs/UserGuide.md
> +Format: `bill INDEX b/BILL`
The `[]` are for optional tags, so they wouldn't apply to the bill command as the input value is required. You may refer to the add vs edit command for the difference

2022-10-18 07:55 UTC, JustinPeng13 commented on src/main/java/seedu/guest/model/guest/Bill.java
> +                    + "If a decimal point is used, there must be 2 digits after it (e.g., 9.99).\n"
Agreed. Also accepted no leading digit before decimal point

2022-10-18 08:45 UTC, JustinPeng13 commented on src/test/java/seedu/guest/logic/commands/BillCommandTest.java
> +    public void execute_invalidGuestIndexFilteredList_failure() {
Yes, added

2022-10-18 09:19 UTC, jehousoh approved these changes
LGTM!

2022-10-18 10:01 UTC, merged